version: "3"

services:
  nginx:
    container_name: livestyle_prod_nginx
    build: ./nginx
    restart: always
    depends_on:
      - client
      - server
    ports:
      - "3050:80"

  client:
    container_name: livestyle_prod_client
    tty: true
    build:
      context: ./client
      dockerfile: prod.Dockerfile
    restart: always
    depends_on:
      - server
    volumes:
      - /app/node_modules
      - ./client:/app

  server:
    container_name: livestyle_prod_server
    build:
      context: ./server
      dockerfile: prod.Dockerfile
    restart: always
    volumes:
      - ./server:/app
