version: "3"

services:
  nginx:
    build: ./nginx
    restart: always
    depends_on:
      - livestyle-client
      - livestyle-server
    ports:
      - "3050:80"

  livestyle-client:
    tty: true
    build:
      context: ./client
      dockerfile: Dockerfile
    restart: always
    depends_on:
      - livestyle-server
    volumes:
      - /app/node_modules
      - ./client:/app

  livestyle-server:
    build:
      context: ./server
      dockerfile: Dockerfile
